import { PrismaClient } from "@prisma/client";

export { PrismaClient };
export type {
  CashMovement,
  CashMovementType,
  ContractFinalizationReason,
  ContractParticipant,
  ContractProperty,
  Currency,
  DepositPact,
  Document,
  DocumentType,
  EconomicIndexType,
  Guarantee,
  GuaranteePropertyBacked,
  GuaranteeSalaryReceipt,
  GuaranteeState,
  GuaranteeSurety,
  GuaranteeTitleHolder,
  GuaranteeType,
  Liquidation,
  LiquidationAdjustmentSign,
  LiquidationLineItem,
  LiquidationManualAdjustment,
  LiquidationStatus,
  Owner,
  Persona,
  PersonaFisica,
  PersonaJuridica,
  PersonaKind,
  Payment,
  PaymentStatus,
  Prisma,
  Property,
  PropertyOwner,
  PropertyService,
  PropertyStatus,
  PropertyType,
  PropertyTypeCatalog,
  RentalContract,
  RentalContractStatus,
  Renter,
  ServiceType,
  Tenant,
  TenantSettings,
  TenantStatus,
  TenantUser,
  User
} from "@prisma/client";

export type PrismaCompatibleClient = PrismaClient;
